[package]
name = "browser-history-rofi"
version = "0.1.0"
edition = "2021"

[dependencies]
rofi-mode = { version = "0.3.0" }
browser-history = { git = "https://github.com/JohnJohnstone/browser-history-rs" }
env_logger = "0.10.0"
log = "0.4.17"

[lib]
crate-type = ["cdylib"]
